INSERT INTO MEMBERS (dni, name, skipper) VALUES('62948577S', 'ALVARO CHAVES AGUILAR', '0');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('11797431H', 'MARIA GLORIA OLIVA VEGA', '1');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('44197751P', 'GREGORIO PACHECO SORIANO', '0');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('36770903K', 'ANTONIO DE LA CRUZ PRADO', '1');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('68010127R', 'RODRIGO DE JUAN FERRER', '0');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('40373765W', 'JONATHAN RINCON BOSCH', '0');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('47091808K', 'ALVARO REYES AULLON', '1');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('25783344E', 'MANUELA PULIDO ARJONA', '0');
INSERT INTO MEMBERS (dni, name, skipper) VALUES('30285895R', 'MONTSERRAT CORRALES ROS', '1');

INSERT INTO SKIPPERS (dni, name, skipper) VALUES('91738185V', 'ANA CAMACHO PEREZ', '1');
INSERT INTO SKIPPERS (dni, name, skipper) VALUES('35938076R', 'MARGARITA GRIFELL RAMOS', '1');
INSERT INTO SKIPPERS (dni, name, skipper) VALUES('05920812Z', 'ROSA MARIA CAMARASSA LLIRIA', '1');
INSERT INTO SKIPPERS (dni, name, skipper) VALUES('30289190F', 'ESTEVE PUIG GONZALEZ', '1');
INSERT INTO SKIPPERS (dni, name, skipper) VALUES('93476119W', 'JOAQUIN MARRERO RODRIGUEZ', '1');
INSERT INTO SKIPPERS (dni, name, skipper) VALUES('48939350L', 'CLAUDIA GUEDES CHAVES', '1');

INSERT INTO BOATS (name, mooringNumber, fee) VALUES('MATADOR', '1', '120.00');
INSERT INTO BOATS (name, mooringNumber, fee) VALUES('PRINCESS', '1', '180.00');
INSERT INTO BOATS (name, mooringNumber, fee) VALUES('GODZILLA', '1', '300.00');
INSERT INTO BOATS (name, mooringNumber, fee) VALUES('DIANA', '1', '100.00');
INSERT INTO BOATS (name, mooringNumber, fee) VALUES('SUPER NOVA', '1', '130.00');
INSERT INTO BOATS (name, mooringNumber, fee) VALUES('QUASIMODO', '1', '150.00');
INSERT INTO BOATS (name, mooringNumber, fee) VALUES('BURRITO', '1', '160.00');